// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3nDc5vFnO0u4_XTbr5BwaQL8s_x7m2aM',
    appId: '1:319466150128:web:abcdef123456', // Placeholder, but ProjectID is critical
    messagingSenderId: '319466150128',
    projectId: 'arfy-ad3a5',
    authDomain: 'arfy-ad3a5.firebaseapp.com',
    storageBucket: 'arfy-ad3a5.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nDc5vFnO0u4_XTbr5BwaQL8s_x7m2aM',
    appId: '1:319466150128:android:359bc12b5e7b8c5d260a35',
    messagingSenderId: '319466150128',
    projectId: 'arfy-ad3a5',
    storageBucket: 'arfy-ad3a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXAMPLE_IOS_API_KEY',
    appId: '1:123456789012:ios:abcdef123456',
    messagingSenderId: '123456789012',
    projectId: 'heraffi-project',
    storageBucket: 'heraffi-project.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.heraffi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEXAMPLE_MACOS_API_KEY',
    appId: '1:123456789012:ios:abcdef123456',
    messagingSenderId: '123456789012',
    projectId: 'heraffi-project',
    storageBucket: 'heraffi-project.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.heraffi',
  );
}
